schedules:
  - cron: '0 20 * * 6'
    displayName: Weekly build
    branches:
     include:
       - master
    always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub - ninckblokje'
    repository: 'ninckblokje/ftp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
